// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubuProtokol.DataAccess.EntityFramework.Context;

#nullable disable

namespace SubuProtokol.DataAccess.Migrations
{
    [DbContext(typeof(Databse1Context))]
    [Migration("20240813134907_testdb")]
    partial class testdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubuProtokol.Entities.EntityFramework.Database1.Protokol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmantType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailImzalananKurum")
                        .HasColumnType("text");

                    b.Property<string>("FileKey")
                        .HasColumnType("text");

                    b.Property<string>("Konu")
                        .HasColumnType("text");

                    b.Property<bool>("MailKontrol")
                        .HasColumnType("boolean");

                    b.Property<int?>("MainSurec")
                        .HasColumnType("integer");

                    b.Property<int?>("MainType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProtokolFinishTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProtokolImzalananKurum")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProtokolStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProtokoldenSorumluKisi")
                        .HasColumnType("text");

                    b.Property<int?>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("Sector")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<int?>("Time")
                        .HasColumnType("integer");

                    b.Property<int?>("UnderType")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<bool?>("arsiv")
                        .HasColumnType("boolean");

                    b.Property<string>("indirimAciklamasi")
                        .HasColumnType("text");

                    b.Property<int?>("parentprotokolid")
                        .HasColumnType("integer");

                    b.Property<int?>("protokolfiltreleme")
                        .HasColumnType("integer");

                    b.Property<bool?>("silindimi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Protokol");
                });

            modelBuilder.Entity("SubuProtokol.Entities.EntityFramework.Database1.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirimTuruAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SabisBirimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("SubuProtokol.Entities.EntityFramework.Database1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SubuProtokol.Entities.EntityFramework.Database1.Protokol", b =>
                {
                    b.HasOne("SubuProtokol.Entities.EntityFramework.Database1.Unit", "Unit")
                        .WithMany("Protokols")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SubuProtokol.Entities.EntityFramework.Database1.Unit", b =>
                {
                    b.Navigation("Protokols");
                });
#pragma warning restore 612, 618
        }
    }
}
